### PR TITLE
add thank you message

### PR DESCRIPTION
**Pull request by mrtingalingling**
@smolgroot Am I doing this right? 

Do we need link 236 to 238? And let me know if I should move the css somewhere else!

### CODE REVIEW

**Comment by mrtingalingling** [comment]
Add a "How it works" button in the solution container?
Redirect to a MD with diagrams show how it works for the host and the users

**Comment by smolgroot** [comment]
> @smolgroot Am I doing this right?
> 
> Do we need link 336 to 338? And let me know if I should move the css somewhere else!

line 336->338 on which file?

**Comment by smolgroot** [comment]
How can we prevent a bad actor to spam our waitlist form? Can we add rule by IP address?

A simple oneliner like this one can be sufficient to bring the mess into the list:

```
watch -n 0.5 "curl 'https://script.google.com/macros/s/AKfycbxgowDv4E0Kqqkex4FjL78XK6DIpRE_6emhaOcs1zQJ_MGDC0mXIKmW_BwA4tH-oswK/exec' \
  --data-raw 'Email=this-field-can-be-spammed%40example.com'"
```

**Comment by mrtingalingling** [comment]
> > @smolgroot Am I doing this right?
> > Do we need link 336 to 338? And let me know if I should move the css somewhere else!
> 
> line 236->238 on which file?

236-238 in src/content/body.astro

**Comment by mrtingalingling** [comment]
> How can we prevent a bad actor to spam our waitlist form? Can we add rule by IP address?
> 
> A simple oneliner like this one can be sufficient to bring the mess into the list:
> 
> ```
> watch -n 0.5 "curl 'https://script.google.com/macros/s/AKfycbxgowDv4E0Kqqkex4FjL78XK6DIpRE_6emhaOcs1zQJ_MGDC0mXIKmW_BwA4tH-oswK/exec' \
>   --data-raw 'Email=this-field-can-be-spammed%40example.com'"
> ```

Let me try! I was trying to use jotform, but it keeps redirecting me unless we upgrade :|

**Comment by mrtingalingling** [comment]
Just checked, looks like I can only use google account as a restriction. Let's use the google for now, I will dig deeper into jot or other form tool and see if we have a different way about it?

**Comment by smolgroot** [comment]
Is this an interesting option? --> https://docs.netlify.com/forms/setup/#app

**Review by smolgroot — APPROVED** [review]

**Pull request merged**
